import re

DOXYFILE = 'Doxyfile-mcss'

MAIN_PROJECT_URL = 'https://github.com/tnagler/RcppThread'

LINKS_NAVBAR1 = [
    ('API', 'namespaceRcppThread', []),
    ('Automatic overrides', 'overrides', [])
]
LINKS_NAVBAR2 = [
    ("<a href=\"https://github.com/tnagler/RcppThread\">GitHub</a>", [])
]

FINE_PRINT = """<p>RcppThread docs. copyright © <a href="http://tnagler.com/">Thomas Nagler</a> 2022.<br />Generated by <a href="https://doxygen.org/">Doxygen</a> {doxygen_version} and <a href="https://mcss.mosra.cz/">m.css</a>. Contact the author via <a href="https://github.com/tnagler/RcppThread">GitHub</a> or  <a href="mailto:mail@tnagler.com">e-mail</a>"""

SEARCH_HELP = """<p class="m-noindent">Search for symbols, directories, files, pages, OpenGL, GLSL, Vulkan and OpenAL APIs. You can omit any prefix from the symbol or file path; adding a <code>:</code> or <code>/</code> suffix lists all members of given symbol or directory.</p> <p class="m-noindent">Use <span class="m-label m-dim">&darr;</span> / <span class="m-label m-dim">&uarr;</span> to navigate through the list, <span class="m-label m-dim">Enter</span> to go. <span class="m-label m-dim">Tab</span> autocompletes common prefix, you can copy a link to the result using <span class="m-label m-dim">⌘</span> <span class="m-label m-dim">L</span> while <span class="m-label m-dim">⌘</span> <span class="m-label m-dim">M</span> produces a Markdown link.</p>"""

VERSION_LABELS = True

SHOW_UNDOCUMENTED = False

FAVICON = 'favicon-dark.png'
