# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testMonitor <- function() {
    invisible(.Call('_RcppThread_testMonitor', PACKAGE = 'RcppThread'))
}

testThreadClass <- function() {
    invisible(.Call('_RcppThread_testThreadClass', PACKAGE = 'RcppThread'))
}

testThreadPoolPush <- function() {
    invisible(.Call('_RcppThread_testThreadPoolPush', PACKAGE = 'RcppThread'))
}

testThreadPoolMap <- function() {
    invisible(.Call('_RcppThread_testThreadPoolMap', PACKAGE = 'RcppThread'))
}

testThreadPoolParallelFor <- function() {
    invisible(.Call('_RcppThread_testThreadPoolParallelFor', PACKAGE = 'RcppThread'))
}

testThreadPoolForEach <- function() {
    invisible(.Call('_RcppThread_testThreadPoolForEach', PACKAGE = 'RcppThread'))
}

testThreadPoolSingleThreaded <- function() {
    invisible(.Call('_RcppThread_testThreadPoolSingleThreaded', PACKAGE = 'RcppThread'))
}

testParallelFor <- function() {
    invisible(.Call('_RcppThread_testParallelFor', PACKAGE = 'RcppThread'))
}

testForEach <- function() {
    invisible(.Call('_RcppThread_testForEach', PACKAGE = 'RcppThread'))
}

testThreadInterrupt <- function() {
    invisible(.Call('_RcppThread_testThreadInterrupt', PACKAGE = 'RcppThread'))
}

testPoolInterruptJoin <- function() {
    invisible(.Call('_RcppThread_testPoolInterruptJoin', PACKAGE = 'RcppThread'))
}

testPoolInterruptWait <- function() {
    invisible(.Call('_RcppThread_testPoolInterruptWait', PACKAGE = 'RcppThread'))
}

