# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testMonitor <- function() {
    invisible(.Call('_RcppThread_testMonitor', PACKAGE = 'RcppThread'))
}

testThreadClass <- function() {
    invisible(.Call('_RcppThread_testThreadClass', PACKAGE = 'RcppThread'))
}

testThreadPoolPush <- function() {
    invisible(.Call('_RcppThread_testThreadPoolPush', PACKAGE = 'RcppThread'))
}

