# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

testMonitor <- function() {
    invisible(.Call('_RcppThreads_testMonitor', PACKAGE = 'RcppThreads'))
}

testThreadClass <- function() {
    invisible(.Call('_RcppThreads_testThreadClass', PACKAGE = 'RcppThreads'))
}

testThreadPool <- function() {
    invisible(.Call('_RcppThreads_testThreadPool', PACKAGE = 'RcppThreads'))
}

